[workspace]
resolver = "3"
members = [
    "runner",
    "p0",
    "p1",
    "p2",
    "p3",
    "p4",
    "p5",
    "p6",
    "p7",
    "p8",
    "p9",
    "p10",
]


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
